### PR TITLE
Fix keyword combinator not to consume following whitespace

### LINKED ISSUE #17: Wrong color and "boldness" in "...>" when line ends with "<>"
(originally posted as https://github.com/elixir-lang/ex_doc/issues/1317)

I was able to create a minimal repro:

```elixir
source = """
iex> x = [
...>   string:
...>     "foo" <>
...>       "bar"
...> ]
"""

html = Makeup.highlight(source)
css = ["<style type=\"text/css\">", Makeup.stylesheet(), "</style>"]
html = [css, html]

File.write!("/tmp/makeup.html", html)
System.cmd("open", ["/tmp/makeup.html"])
```

image

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #17.

### CODE REVIEW

File: test/makeup/lexers/elixir_lexer/elixir_lexer_tokenizer_test.exs [hunk 1]
```diff
@@ -50,6 +50,37 @@ defmodule ElixirLexerTokenizerTestSnippet do
       assert lex("...(12)> ") == [{:generic_prompt, %{selectable: false}, "...(12)> "}]
     end
 
+    test "parses multiline iex prompt correctly" do
+      source = """
+      iex> x = [
+      ...>   key:
```
Comment (jonatanklosko) [inline test/makeup/lexers/elixir_lexer/elixir_lexer_tokenizer_test.exs:56]: Previously the `keyword` tokenizer would consume `key:` and also the newline. However, the newline is important for the iex prompt to match:

https://github.com/elixir-makeup/makeup_elixir/blob/899866c8a2e97b6a6c11f1722d1d842092367362/lib/makeup/lexers/elixir_lexer.ex#L311-L313

As a result the above wouldn't match and `...` would be tokenized as `:name`.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
